---
- name: Install packages
  hosts: all
  become: true
  tasks:
  - name: install
    become: true
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - ruby-full
        - ruby-bundler
        - build-essential
