- name: Add unit file for Puma
  become: true
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
    mode: 0644  # <-- Права на файл, которые нужно установить
  notify: reload puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    mode: 0644  # <-- Права на файл, которые нужно установить
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  notify: reload puma

- name: enable puma
  become: true
  systemd:
    daemon_reload: true
    name: puma
    enabled: true
