- name: install
  become: true
  tags: ruby
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - ruby-full
      - ruby-bundler
      - build-essential
