---
- name: Configure app
  hosts: app
  become: yes
  tags: app-tag
  vars:
    db_host: 178.154.240.185
  tasks:
    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config

    - name: enable puma
      become: true
      systemd:
        daemon_reload: yes
        name: puma
        enabled: yes

  handlers:
    - name: reload puma
      become: true
      service:
        name: puma
        state: restarted
